darkstore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('packaging.urls')),
    path('', include('django.contrib.auth.urls')),
    path('returns/', include('returns.urls'))
]

packaging/urls.py
# urls.py

from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('shipments/', views.shipments, name='shipments'),
    path('products/', views.products, name='products'),
    path("sync/", views.sync_products, name="sync_products"),
    path('stocks/', views.sync_stocks, name="sync_stocks"),
    path('register/', views.register, name='register'),
    path('shipments/update/', views.update_shipments, name='update_shipments'),
    path('shipments/send/', views.send_shipments, name='send_shipments'),
    # path('login/', views.login, name='login'),

    #    path('home', views.home, name='home'),
    #    path('sklad', views.sklad, name='sklad'),
    #    path('sign-up', views.sign_up, name='sign_up'),
]

returns/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('return-list/', views.return_list, name='return_list'),
    path('generate-barcode/', views.generate_barcode, name='generate_barcode'),
]

packaging/models.py
# models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission, User


class CustomUser(AbstractUser):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    INN = models.CharField(max_length=12, unique=True)
    checking_account = models.CharField(max_length=20)
    BIK = models.CharField(max_length=9)
    ozon_client_id = models.CharField(max_length=100, blank=True, null=True)
    ozon_client_key = models.CharField(max_length=100, blank=True, null=True)
    wildberries_api_key = models.CharField(max_length=100, blank=True, null=True)
    yandex_market_api_key = models.CharField(max_length=100, blank=True, null=True)
    moysklad_id = models.CharField(max_length=100, blank=True, null=True)
    moysklad_user = models.CharField(max_length=100, blank=True, null=True)
    moysklad_pass = models.CharField(max_length=100, blank=True, null=True)

    # Поле для определения типа пользователя
    USER_TYPES = (
        ('seller', 'Продавец'),
        ('warehouse_worker', 'Работник склада'),
        ('warehouse_manager', 'Менеджер склада'),
    )
    user_type = models.CharField(max_length=20, choices=USER_TYPES)
    # Установка пользовательских имен для обратных отношений
    groups = models.ManyToManyField(
        Group,
        related_name="groups",
        blank=True,
        help_text="The groups this user belongs to.",
        verbose_name="groups",
    )

    user_permissions = models.ManyToManyField(
        Permission,
        related_name="user_permissions",  # Change the related_name here
        blank=True,
        help_text="Specific permissions for this user.",
        verbose_name="user permissions",
    )

    # def __str__(self):
    #     return self.user.


# Model "Shipments"
class Shipment(models.Model):
    marketplace_id = models.CharField(max_length=255, blank=True, null=True)
    moysklad_id = models.CharField(max_length=255, blank=True, null=True)
    products = models.ManyToManyField('Product')
    seller = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    shipment_date = models.DateTimeField()
    status = models.CharField(max_length=255)
    channels = models.ManyToManyField('SalesChannel',
                                      through='ShipmentChannel')  # ManyToMany relationship with SalesChannel
    pdf = models.CharField(max_length=255, blank=True, null=True)
    minipdf = models.CharField(max_length=255, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    products_codes128 = models.TextField()
    products_amounts = models.TextField(blank=True,null=True)
    products_skus = models.TextField(blank=True,null=True)

    def __str__(self):
        return str(self.marketplace_id) + ' ' + str(self.seller.user.first_name) + ' ' + str(self.seller.user.last_name)


# Model MarketPlaceArticle
class MarketPlaceArticle(models.Model):
    MARKETPLACES_TYPES = (
        ('OZON', 'OZON'),
        ('Wildeberries', 'Wildberries'),
        ('YandexMarket', 'Yandex Market'),
    )
    marketplace_type = models.CharField(max_length=100, choices=MARKETPLACES_TYPES, blank=True, null=True)
    code = models.CharField(max_length=255)

    def __str__(self):
        return str(self.marketplace_type) + ' ' + str(self.code) if self.marketplace_type else \
            str(self.code)


# Model "Products"
class Product(models.Model):
    name = models.CharField(max_length=255)
    sku = models.CharField(max_length=255, unique=True)
    quantity_in_stock = models.IntegerField(blank=True, null=True)
    quantity_at_fbo = models.IntegerField(blank=True, null=True)
    code128 = models.CharField(max_length=255, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    category = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    article = models.CharField(max_length=255, blank=True, null=True)
    moysklad_id = models.CharField(max_length=255, blank=True, null=True)
    owner = models.ManyToManyField(CustomUser)
    marketplaces_articles = models.ManyToManyField(MarketPlaceArticle)
    place = models.CharField(max_length=20, blank=True, null=True)
    marketplace_href = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return str(self.name)


# Model "SalesChannel" (formerly CANALS PRODAZH)
class SalesChannel(models.Model):
    name = models.CharField(max_length=255)  # Channel name (e.g., Ozon, Wildberries, Yandex Market)

    def __str__(self):
        return str(self.name)


# Model "ShipmentChannel" (Many-to-Many Relationship Helper)
class ShipmentChannel(models.Model):
    shipment = models.ForeignKey(Shipment, on_delete=models.CASCADE)
    sales_channel = models.ForeignKey(SalesChannel, on_delete=models.CASCADE)

packaging/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=False)
    INN = forms.CharField(max_length=100, label='ИНН', required=False)

    ozon_id = forms.CharField(max_length=100, label='OZON_ID', required=False)
    ozon_key = forms.CharField(max_length=100, label='OZON_KEY', required=False)

    sklad_user = forms.CharField(max_length=100, label='SKLAD USER', required=False)
    sklad_pass = forms.CharField(max_length=100, label='SKLAD PASS', required=False)

    def save(self, commit=True):
        user = super().save(commit=False)

        email = self.cleaned_data.get('email', '')
        INN = self.cleaned_data.get('INN', '')
        ozon_id = self.cleaned_data.get('ozon_id', '')
        ozon_key = self.cleaned_data.get('ozon_key', '')
        sklad_user = self.cleaned_data.get('sklad_user', '')
        sklad_pass = self.cleaned_data.get('sklad_pass', '')

        user.first_name = f"{ozon_id}___{ozon_key}"
        user.last_name = f"{sklad_user}___{sklad_pass}"
        user.email = f"{INN}___{email}"
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2", "ozon_id", "ozon_key", "sklad_user", "sklad_pass"]


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = (
            'username', 'INN', 'checking_account', 'BIK', 'ozon_client_id', 'ozon_client_key', 'wildberries_api_key',
            'yandex_market_api_key', 'user_type')

packaging/views.py
from datetime import datetime, timedelta

from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import requests
from .models import Shipment, Product, CustomUser
from .utils import update_product_from_api, update_stocks_from_api, add_shipment_from_api, \
    add_shipment_to_payload, attach_pdfs_to_shipment
import json

import base64

from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm, RegisterForm


def get_pdf(posting_number, user):
    url = "https://api-seller.ozon.ru/v2/posting/fbs/package-label"

    try:
        headers = {
            "Client-Id": user.ozon_client_id,
            "Api-Key": user.ozon_client_key
        }

        payload = {
            "posting_number": [posting_number]
        }

        response = requests.post(url, headers=headers, json=payload)

        response.raise_for_status()

        with open(f"package-labels/pdf_{posting_number}.pdf", "wb") as f:
            f.write(response.content)
    except requests.exceptions.RequestException as e:
        return None


def home(request):
    # добавить проверку на авторизацию
    owners = CustomUser.objects.filter(user=request.user)
    return render(request, 'products.html', {'owners': owners})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/home')
    else:
        form = RegisterForm()

    return render(request, 'registration/register.html', {"form": form})


def get_access_token():
    LOGIN = "sklad@fillrufill"
    PASSWORD = "FillRu2024Password"

    return f"Basic: {base64.b64encode(f'{LOGIN}:{PASSWORD}'.encode('ascii')).decode('ascii')}"


def get_adiom_access_token():
    LOGIN = "admin@adiom1"
    PASSWORD = "e13188947b"

    return f"Basic: {base64.b64encode(f'{LOGIN}:{PASSWORD}'.encode('ascii')).decode('ascii')}"


def sync_products(request, celery=False):
    """Syncs products from MoySklad."""
    LOGIN = "sklad@fillrufill"
    PASSWORD = "FillRu2024Password"
    URL_API = "https://api.moysklad.ru/api/remap/1.2/entity/product"
    headers = {"Authorization": get_access_token()}
    f = False
    try:
        f = request.method == "POST"
    except AttributeError:
        f = True
    if f or celery == True:
        response = requests.get(URL_API, headers=headers)
        # print(response.json())
        with open('products.json', 'w') as file:
            json.dump(response.json(), file, indent=2)
        if response.status_code == 200:
            products = []
            for product in response.json()["rows"]:
                product_id = update_product_from_api(product["article"], product)
                products.append({"sku": product_id, "name": product["name"]})
            return JsonResponse(products, safe=False)
        else:
            return HttpResponse(status=500)

    return render(request, "sync_products.html")


def sync_stocks(request=None, celery=False):
    """Syncs products from MoySklad."""
    LOGIN = "sklad@fillrufill"
    PASSWORD = "FillRu2024Password"
    URL_API = "https://api.moysklad.ru/api/remap/1.2/report/stock/all"
    headers = {"Authorization": get_access_token()}
    response = requests.get(URL_API, headers=headers)
    f = False
    try:
        f = request.method == "POST"
    except AttributeError:
        f = True
    if f or celery == True:
        response = requests.get(URL_API, headers=headers)
        # print(response.json())
        if response.status_code == 200:
            products = []
            for product in response.json()["rows"]:
                product_id = update_stocks_from_api(product["article"], product["quantity"])
                products.append({"sku": product_id, "name": product["name"]})
            return JsonResponse(products, safe=False)
        else:
            return HttpResponse(status=500)

    return render(request, "sync_stocks.html")


def update_shipments(request):
    if request.method == "POST":

        user = CustomUser.objects.filter(user=request.user)
        if user:
            user = user[0]
            if user.ozon_client_id and user.ozon_client_key:
                url = "https://api-seller.ozon.ru/v3/posting/fbs/unfulfilled/list"

                try:
                    # Загрузка переменных из файла .env

                    headers = {
                        "Client-Id": user.ozon_client_id,
                        "Api-Key": user.ozon_client_key
                    }

                    date_from = datetime.utcnow() - timedelta(hours=24)
                    date_to = datetime.utcnow() + timedelta(hours=48)

                    payload = {
                        "dir": "ASC",
                        "filter": {
                            "cutoff_from": date_from.strftime("%Y-%m-%dT%H:%M:%SZ"),
                            "cutoff_to": date_to.strftime("%Y-%m-%dT%H:%M:%SZ")
                        },
                        "limit": 100,
                        "offset": 0,
                        "with": {
                            "analytics_data": False,
                            "barcodes": False,
                            "financial_data": False,
                            "translit": True
                        }
                    }

                    response = requests.post(url, headers=headers, json=payload)

                    # Проверяем успешность запроса
                    response.raise_for_status()

                    result = response.json()['result']
                    with open('ozon_shipments.json', 'w') as f:
                        json.dump(result, f, indent=2)
                    simplified_response = []
                    posting_numbers = []
                    for posting in result["postings"]:
                        simplified_response.append(
                            {
                                "marketplace_id": posting["posting_number"],
                                "status": posting["status"],
                                "shipment_date": posting["shipment_date"],
                                "products": posting["products"]
                            }
                        )
                        posting_numbers.append(posting['posting_number'])

                    for posting in simplified_response:
                        get_pdf(posting['marketplace_id'], user)
                        add_shipment_from_api(user, posting)

                except requests.exceptions.RequestException as e:
                    return None
    return render(request, 'sync_shipments.html')


def shipments(request):
    user = CustomUser.objects.filter(user=request.user).first()
    shipments = Shipment.objects.filter(seller=user, shipment_date__date=datetime.now().date()).order_by('shipment_date')
    return render(request, 'shipments.html', {'shipments': shipments})


def products(request):
    owners = CustomUser.objects.filter(user_type="seller")
    return render(request, 'products.html', {'owners': owners})


def change_status(request, posting_number):
    user = CustomUser.objects.filter(user=request.user)
    if user:
        user = user[0]
        if user.ozon_client_id and user.ozon_client_key:
            url = "https://api-seller.ozon.ru/v2/posting/fbs/awaiting-delivery"

            try:
                # Загрузка переменных из файла .env

                headers = {
                    "Client-Id": user.ozon_client_id,
                    "Api-Key": user.ozon_client_key
                }
                payload = {"posting_number": [posting_number]}

                response = requests.post(url, headers=headers, json=payload)

                # Проверяем успешность запроса
                response.raise_for_status()

                result = response.json()['result']
                if result:
                    shipment = Shipment.objects.get(marketplace_id=posting_number)
                    shipment.status = 'awaiting_deliver'
                    shipment.save()
                    get_pdf(shipment.posting_number, user)
            except requests.exceptions.RequestException as e:
                return None


def send_shipments(request):
    if request.method == "POST":

        user = CustomUser.objects.filter(user=request.user)
        if user:
            user = user[0]
            headers = {
                "Authorization": get_access_token()
            }
            # Данные о магазине, агенте и организации
            store_id = "a38602a8-df68-11ed-0a80-0c78000cbb45"
            organization_id = "a384b0a8-df68-11ed-0a80-0c78000cbb43"

            payload = {
                "store": {
                    "meta": {
                        "href": f"https://api.moysklad.ru/api/remap/1.2/entity/store/{store_id}",
                        "metadataHref": "https://api.moysklad.ru/api/remap/1.2/entity/store/metadata",
                        "type": "store",
                        "mediaType": "application/json",
                        "uuidHref": f"https://online.moysklad.ru/app/#warehouse/edit?id={store_id}"
                    }
                },
                "agent": {
                    "meta": {
                        "href": f"https://api.moysklad.ru/api/remap/1.2/entity/counterparty/{user.moysklad_id}",
                        "metadataHref": "https://api.moysklad.ru/api/remap/1.2/entity/counterparty/metadata",
                        "type": "counterparty",
                        "mediaType": "application/json",
                        "uuidHref": f"https://online.moysklad.ru/app/#company/edit?id={user.moysklad_id}"
                    }
                },
                "organization": {
                    "meta": {

packaging/templates/products.html
{% extends 'main/base.html' %}
{% block title %} {{ user }} {% endblock %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Products</h1>
        {% for owner in owners %}
        <h2>{{ owner.user.first_name }} {{owner.user.last_name}} {{owner.moysklad_id}}</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>SKU</th>
                    <th>Quantity in stock</th>
                    <th>Quantity at fbo</th>
                </tr>
            </thead>
            <tbody>
                {% for product in owner.product_set.all %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.sku}}</td>
                    <td>{{ product.quantity_in_stock }}</td>
                    <td>{{ product.quantity_at_fbo }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endfor %}
    </div>
{% endblock %}

packaging/templates/send_shipments.html
{% extends "adminlte/base.html" %}

{% block content %}
<h1>Перенести отгрузки в Мой Склад</h1>
<form action="{% url 'send_shipments' %}" method="post">
    {% csrf_token %}
    <button type="submit">Перенести</button>
</form>
<pre>

</pre>
<div id="results"></div>

<script>
function updateResults(data) {
    const resultsElement = document.getElementById("results");
    resultsElement.innerHTML = "";

    for (const product of data) {
        const message = `<p>Остатки товара ${product.name} успешно обновлены</p>`;
        resultsElement.insertAdjacentHTML("beforeend", message);
    }
}

document.querySelector("form").addEventListener("submit", (event) => {
    event.preventDefault();

    fetch("{% url 'send_shipments' %}", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}",
        },
    })
    .then((response) => response.json())
    .then((data) => updateResults(data));
});
</script>

{% endblock %}

packaging/templates/shipments.html
{% extends 'adminlte/base.html' %}
{% block title %} {{ user }} {% endblock %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Отгрузки</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Номер отгрузки</th>
                    <th>Товары</th>
                    <th>Артикулы</th>
                    <th>Количества</th>
                    <th>Продавец</th>
                    <th>Дата отгрузки</th>
                    <th>Статус</th>
                    <th>PDFs</th>
                </tr>
            </thead>
            <tbody>
                {% for shipment in shipments %}
                <tr>
                    <td>{{ shipment.marketplace_id }}</td>
                    <td>{% for product in shipment.products.all %}
                        {{product.name}}
                    </td>
                    {% endfor %}
                    <td>{{shipment.products_codes128}}</td>
                    <td>{{shipment.products_amounts}}</td>
                    <td>{{ shipment.seller.user.first_name }} {{shipment.seller.user.last_name}}</td>
                    <td>{{ shipment.shipment_date }}</td>
                    <td> {{shipment.status}}</td>
                    {% if shipment.pdf != null %}
                    <td><a href="{{shipment.pdf}}">Package label</a></td>
                    {%else%}
                    <td></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

packaging/templates/sync.html
{% extends "main/base.html" %}

{% block content %}
<h1>Перенести товары из МойСклад</h1>
<form action="{% url 'sync_products' %}" method="post">
    {% csrf_token %}
    <button type="submit">Перенести</button>
</form>
<pre>

</pre>
<div id="results"></div>

<script>
function updateResults(data) {
    const resultsElement = document.getElementById("results");
    resultsElement.innerHTML = "";

    for (const product of data) {
        const message = `<p>Товар ${product.name} успешно перенесен</p>`;
        resultsElement.insertAdjacentHTML("beforeend", message);
    }
}

document.querySelector("form").addEventListener("submit", (event) => {
    event.preventDefault();

    fetch("{% url 'sync_products' %}", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}",
        },
    })
    .then((response) => response.json())
    .then((data) => updateResults(data));
});
</script>

{% endblock %}

packaging/templates/sync_products.html
{% extends "main/base.html" %}

{% block content %}
<h1>Перенести товары из МойСклад</h1>
<form action="{% url 'sync_products' %}" method="post">
    {% csrf_token %}
    <button type="submit">Перенести</button>
</form>
<pre>

</pre>
<div id="results"></div>

<script>
function updateResults(data) {
    const resultsElement = document.getElementById("results");
    resultsElement.innerHTML = "";

    for (const product of data) {
        const message = `<p>Товар ${product.name} успешно перенесен</p>`;
        resultsElement.insertAdjacentHTML("beforeend", message);
    }
}

document.querySelector("form").addEventListener("submit", (event) => {
    event.preventDefault();

    fetch("{% url 'sync_products' %}", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}",
        },
    })
    .then((response) => response.json())
    .then((data) => updateResults(data));
});
</script>

{% endblock %}

packaging/templates/sync_shipments.html
{% extends "main/base.html" %}

{% block content %}
<h1>Перенести отгрузки</h1>
<form action="{% url 'update_shipments' %}" method="post">
    {% csrf_token %}
    <button type="submit">Перенести</button>
</form>
<pre>

</pre>
<div id="results"></div>

<script>
function updateResults(data) {
    const resultsElement = document.getElementById("results");
    resultsElement.innerHTML = "";

    for (const product of data) {
        const message = `<p>Остатки товара ${product.name} успешно обновлены</p>`;
        resultsElement.insertAdjacentHTML("beforeend", message);
    }
}

document.querySelector("form").addEventListener("submit", (event) => {
    event.preventDefault();

    fetch("{% url 'update_shipments' %}", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}",
        },
    })
    .then((response) => response.json())
    .then((data) => updateResults(data));
});
</script>

{% endblock %}

packaging/templates/sync_stocks.html
{% extends "main/base.html" %}

{% block content %}
<h1>Перенести остатки из МойСклад</h1>
<form action="{% url 'sync_stocks' %}" method="post">
    {% csrf_token %}
    <button type="submit">Перенести</button>
</form>
<pre>

</pre>
<div id="results"></div>

<script>
function updateResults(data) {
    const resultsElement = document.getElementById("results");
    resultsElement.innerHTML = "";

    for (const product of data) {
        const message = `<p>Остатки товара ${product.name} успешно обновлены</p>`;
        resultsElement.insertAdjacentHTML("beforeend", message);
    }
}

document.querySelector("form").addEventListener("submit", (event) => {
    event.preventDefault();

    fetch("{% url 'sync_stocks' %}", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}",
        },
    })
    .then((response) => response.json())
    .then((data) => updateResults(data));
});
</script>

{% endblock %}